---
include:
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/PreCommit.gitlab-ci.yml"
  - remote: "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/SonarScanner.gitlab-ci.yml"

variables:
  CONTAINER_TEST_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  FF_NETWORK_PER_BUILD: "true"

default:
  tags:
    - docker

build_test:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CONTAINER_TEST_IMAGE" || true
    - docker build -t sds .
    - docker build -t "$CONTAINER_TEST_IMAGE" tests
    - docker push "$CONTAINER_TEST_IMAGE"

test:
  stage: test
  image: "$CONTAINER_TEST_IMAGE"
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
      alias: elasticsearch
      command:
        [
          "bin/elasticsearch",
          "-Expack.security.enabled=false",
          "-Expack.security.http.ssl.enabled=false",
          "-Ediscovery.type=single-node",
        ]
    - name: $CONTAINER_TEST_IMAGE
      alias: sds_indexer
      command: ["uvicorn", "indexer:app", "--host", "0.0.0.0", "--port", "8000"]
    - name: $CONTAINER_TEST_IMAGE
      alias: sds_retriever
      command: ["uvicorn", "retriever:app", "--host", "0.0.0.0", "--port", "8001"]
  variables:
    STORAGE_PATH: /data
    ELASTIC_URL: "http://elasticsearch:9200"
  script:
    - cp -R tests app/
    - cd app
    - python -m pytest --junitxml=junit.xml --cov-config tests/.coveragerc --cov-report xml --cov '.'
  artifacts:
    paths:
      - app/junit.xml
      - app/coverage.xml
    reports:
      junit: app/junit.xml
    expire_in: 1 hour
