version: '3'
services:
  sds_indexer:
    image: sds_indexer
    build:
      context: .
      dockerfile: ./indexer/Dockerfile
    ports:
      - "8000:8000"
    environment:
      ELASTIC_URL: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  sds_retriever:
    image: sds_retriever
    build:
      context: .
      dockerfile: ./retriever/Dockerfile
    ports:
      - "8001:8000"
    environment:
      ELASTIC_URL: "http://elasticsearch:9200"
      STORAGE_PATH: ${STORAGE_PATH:?}
    volumes:
      - type: bind
        source: ./test_ioc/storage_test/data
        target: /data
    depends_on:
      - elasticsearch

  sds_collector:
    image: sds_collector
    build:
      context: ./collector
    ports:
      - "8002:8000"
    environment:
      INDEXER_URL: "http://sds_indexer:8000"
      COLLECTOR_DEFINITIONS: "/app/config/collectors.json"
      STORAGE_PATH: ${STORAGE_PATH:?}
    volumes:
      - ./collectors.json:/app/config/collectors.json
    depends_on:
      - sds_indexer

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.2.0"
    container_name: elasticsearch
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock: -1
      nofile: 65536
      nproc: 4096
