version: '3'
services:
  sds_indexer:
    image: sds
    container_name: sds_indexer
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      ELASTIC_URL: "http://elasticsearch:9200"
    command: uvicorn indexer:app --host 0.0.0.0 --port ${INDEXER_PORT:-"8000"}
    depends_on:
      - elasticsearch

  sds_retriever:
    image: sds
    container_name: sds_retriever
    environment:
      ELASTIC_URL: "http://elasticsearch:9200"
      STORAGE_PATH: /data
    command: uvicorn retriever:app --host 0.0.0.0 --port ${RETRIEVER_PORT:-"8000"}
    volumes:
      - type: bind
        source: ${STORAGE_PATH:?}
        target: /data
    depends_on:
      - elasticsearch

  sds_collector:
    image: sds
    container_name: sds_collector
    ports:
      - "8002:8000"
    environment:
      INDEXER_URL: "http://sds_indexer:8000"
      COLLECTOR_DEFINITIONS: "/app/config/collectors.json"
      STORAGE_PATH: /data
    command: python -m collector.main
    volumes:
      - ./collectors.json:/app/config/collectors.json
      - type: bind
        source: ${STORAGE_PATH:?}
        target: /data
    depends_on:
      - sds_indexer

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.3.3"
    container_name: elasticsearch
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m    
    ulimits:
      memlock: -1
      nofile: 65536
      nproc: 4096
