version: '3'
services:
  sds_indexer:
    volumes:
      - ./app:/app/
      - ./test:/test/
    command: uvicorn indexer:app --host 0.0.0.0 --port 8000 --reload

  sds_retriever:
    ports:
      - "8001:8001"
    expose:
      - "8001"
    volumes:
      - ./app:/app/
      - ./test:/test/
    command: uvicorn retriever:app --host 0.0.0.0 --port 8001 --reload

  sds_collector:
    volumes:
      - ./app:/app/
    command: python -m collector.main --reload

  sds_tests:
    image: sds_test
    container_name: sds_tests
    environment:
      INDEXER_URL: "http://0.0.0.0:8000"
      COLLECTOR_DEFINITIONS: "collectors.json"
      ELASTIC_URL: "http://elasticsearch:9200"
      STORAGE_PATH: /data
    volumes:
      - ./data:/data/
      - ./app:/app/
      - ./tests:/app/tests/
      - ./test_ioc/:/app/test_ioc/
      - ./tests/collectors.json:/app/collectors.json
    command: python -m pytest --ignore tests/performance --junitxml=junit.xml --cov-config tests/.coveragerc --cov-report html --cov '.'

  sds_test_ioc:
    image: sds_test
    container_name: sds_test_ioc
    volumes:
      - ./test_ioc/:/app/test_ioc/
      - ./collectors.json:/app/collectors.json
    command: python test_ioc/pva_server.py
    network_mode: "host"

  elasticsearch:
    volumes:
      - ./esdata:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
