version: '3'
services:
  sds_indexer:
    image: sds_indexer:development
    build:
      context: .
      dockerfile: ./indexer/Dockerfile
    volumes:
      - ./indexer:/app/indexer
      - ./common:/app/common
    command: uvicorn indexer:app --host 0.0.0.0 --port 8000 --reload
  
  sds_retriever:
    image: sds_retriever:development
    build:
      context: .
      dockerfile: ./retriever/Dockerfile
    volumes:
      - ./retriever:/app/retriever
      - ./common:/app/common
    command: uvicorn retriever:app --host 0.0.0.0 --port 8000 --reload

  sds_collector:
    image: sds_collector:development
    build:
      context: .
      dockerfile: ./collector/Dockerfile
    volumes:
      - ./collector:/app/collector
      - ./common:/app/common
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
