version: '3'
services:
  sds_indexer:
    volumes:
      - ./src/esds:/app/esds
    command: uvicorn esds.indexer:app --host 0.0.0.0 --port 8000 --reload

  sds_retriever:
    volumes:
      - ./src/esds:/app/esds
    command: uvicorn esds.retriever:app --host 0.0.0.0 --port 8000 --reload

  sds_collector:
    volumes:
      - ./src/esds:/app/esds
    command: python -m esds.collector.main --reload
    network_mode: "host"

  elasticsearch:
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: "docker.elastic.co/kibana/kibana:8.15.2"
    container_name: kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
  
  test_ioc:
    build: "."
    image: sds
    command: python -m test_ioc.pva_server 5 10
    volumes:
      - ./tests/test_ioc/:/app/test_ioc/
    network_mode: "host"
  
  test_ioc_types:
    build: "."
    image: sds
    command: python -m test_ioc.pva_server_multi_type
    volumes:
      - ./tests/test_ioc/:/app/test_ioc/
    network_mode: "host"

volumes:
  esdata:
    driver: local
