version: '3'
services:
  sds_indexer:
    volumes:
      - ./app:/app/
      - ./test:/test/
    command: uvicorn indexer:app --host 0.0.0.0 --port 8000 --reload

  sds_retriever:
    volumes:
      - ./app:/app/
      - ./test:/test/
    command: uvicorn retriever:app --host 0.0.0.0 --port 8000 --reload

  sds_collector:
    volumes:
      - ./app:/app/
    command: python -m collector.main --reload

  sds_tests:
    image: sds_test
    container_name: sds_tests
    environment:
      ELASTIC_URL: "http://elasticsearch:9200"
    volumes:
      - ./app:/app/
      - ./tests:/app/tests/
    command: python -m pytest -v

  elasticsearch:
    volumes:
      - ./esdata:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
