version: '3'
services:
  sds_indexer:
    volumes:
      - ./app:/app/
    command: uvicorn indexer:app --host 0.0.0.0 --port 8000 --reload

  sds_retriever:
    environment:
      STORAGE_PATH: "/data"
    volumes:
      - ./app:/app/
    command: uvicorn retriever:app --host 0.0.0.0 --port 8000 --reload

  sds_collector:
    environment:
      STORAGE_PATH: "/data"
    volumes:
      - ./app:/app/
    command: python -m collector.main --reload
