version: '3'
services:
  sds_indexer:
    volumes:
      - ./src:/app/
    command: uvicorn sds.indexer:app --host 0.0.0.0 --port 8000 --reload

  sds_retriever:
    volumes:
      - ./src:/app/
    command: uvicorn sds.retriever:app --host 0.0.0.0 --port 8000 --reload

  sds_collector:
    volumes:
      - ./src:/app/
    command: python -m sds.collector.main --reload
    network_mode: "host"

  elasticsearch:
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: "docker.elastic.co/kibana/kibana:8.6.2"
    container_name: kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
  
  test_ioc:
    build: "."
    image: sds
    container_name: sds_test_ioc
    command: python test_ioc/pva_server.py 5 10
    volumes:
      - ./tests/test_ioc/:/app/test_ioc/
    network_mode: "host"

volumes:
  esdata:
    driver: local
