version: '3'
services:
  sds_tests:
    build: "./tests"
    image: sds_test
    container_name: sds_tests
    environment:
      INDEXER_URL: "http://0.0.0.0:8000"
      COLLECTOR_DEFINITIONS: "/app/config/collectors.json"
      ELASTIC_URL: "http://elasticsearch:9200"
      STORAGE_PATH: /data
    volumes:
      - ./data:/data/
      - ./src:/app/
      - ./tests:/app/tests/
      - ./tests/test_ioc/:/app/test_ioc/
      - ./tests/collectors.json:/app/config/collectors.json
    command: python -m pytest --ignore tests/performance --junitxml=junit.xml --cov-config tests/.coveragerc --cov-report html --cov '.'

  elasticsearch:
    volumes:
      - ./esdata:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
