version: '3'
services:
  sds_indexer:
    build: "."
    image: sds
    container_name: sds_indexer
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      ELASTIC_URL: "http://elasticsearch:9200"
    command: uvicorn sds.indexer:app --host 0.0.0.0 --port ${INDEXER_PORT:-"8000"}

  sds_retriever:
    build: "."
    image: sds
    container_name: sds_retriever
    ports:
      - "8001:8000"
    environment:
      ELASTIC_URL: "http://elasticsearch:9200"
      STORAGE_PATH: /data
    command: uvicorn sds.retriever:app --host 0.0.0.0 --port ${RETRIEVER_PORT:-"8000"}
    volumes:
      - type: bind
        source: ${STORAGE_PATH:?}
        target: /data

  sds_collector:
    build: "."
    image: sds
    container_name: sds_collector
    network_mode: "host"
    environment:
      INDEXER_URL: "http://127.0.0.1:8000"
      COLLECTOR_DEFINITIONS: "/app/config/collectors.json"
      STORAGE_PATH: /data
      COLLECTOR_API_PORT: 8003
    command: python -m sds.collector.main
    volumes:
      - ./collectors.json:/app/config/collectors.json
      - type: bind
        source: ${STORAGE_PATH:?}
        target: /data
    network_mode: "host"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.6.2"
    container_name: elasticsearch
    ports:
      - "9200:9200"
    expose:
      - "9200"
    environment:
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m    
    ulimits:
      memlock: -1
      nofile: 65536
      nproc: 4096
