name: sds
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles
  - aiohttp
  - elasticsearch
  - fastapi   
  - nexusformat
  - pip
  - python=3.10
  - requests
  - uvicorn
  - pip:
    - --index-url https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple
    - p4p==4.1.1
