version: '3'
services:
  sds_storage:
    image: sds_storage
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.2.0"
    container_name: elasticsearch
    expose:
      - "9200"
    environment:
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock: -1
      nofile: 65536
      nproc: 4096
