name: sds_storage
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.8
  - pip:
    - --index-url https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple
    - elasticsearch==8.2.0
    - fastapi==0.76.0
    - requests==2.27.1
    - uvicorn==0.17.6
