name: sds_retriever
channels:
  - defaults
dependencies:
  - h5py=3.6.0
  - hdf5=1.10.6
  - numpy=1.21.5
  - pip=21.2.4
  - python=3.8
  - pip:
    - --index-url https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple
    - elasticsearch==8.2.0
    - ess-nexus==0.9.5
    - fastapi==0.76.0
    - requests==2.27.1
    - uvicorn==0.17.6
