name: sds
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles
  - aiohttp
  - elasticsearch
  - fastapi   
  - h5py
  - pip
  - python=3.10
  - requests
  - uvicorn
  - gcc
  - gxx
  - pip:
    - --index-url https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple
    - p4p==4.1.5
    - pvxslibs>=1.1.3
