name: sds
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles
  - aiohttp
  - elasticsearch
  - fastapi==0.98.0   
  - h5py
  - pip
  - python=3.10
  - requests
  - uvicorn
  - gcc=12
  - gxx=12
  - pip:
    - --index-url https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple
    - p4p==4.1.7
    - pvxslibs==1.2.2
